os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build test -project CuePointsTracker.xcodeproj -scheme "CI" -destination "platform=iOS Simulator,OS=12.2,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 
